version: '3.2'

services:
   db_mysql_reseller_v1:
      image: mysql:8.0
      container_name: mysql_server_radius_reseller_v1
      restart: always
      ports:
       - '9903:3306'
      environment:
        MYSQL_ROOT_PASSWORD: 'toor'

   app:
      depends_on:
       - db_mysql_reseller_v1
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_radius_reseller_v1
      restart: always
      ports:
       - '8800:80'
      environment:
        PMA_HOST: db_mysql_reseller_v1