version: '3.2'

services:
   db_mysql_reseller:
      image: mysql:8.0
      container_name: mysql_server_radius_reseller
      restart: always
      volumes: 
         - /home/rhein/Programing/Golang/go-insinyur-radius/mysql:/var/lib/mysql
      ports:
       - '9903:3306'
      environment:
        MYSQL_ROOT_PASSWORD: 'toor'

   app:
      depends_on:
       - db_mysql_reseller
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_radius_reseller
      restart: always
      ports:
       - '8800:80'
      environment:
        PMA_HOST: db_mysql_reseller